version: '3.8'
services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "../..:/workspaces:cached"
    hostname: devcontainer
    command: sleep infinity
    environment:
      TZ: "${TZ:-Europe/Warsaw}"
    # NVIDIA GPU access
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 0
    #           capabilities: [gpu]